module.exports = {
  roots: ['<rootDir>'],
  testMatch: ['**/tests/**/*.(spec|test).+(ts|tsx|js)'],
  testPathIgnorePatterns: [
    '<rootDir>/build/',
    '<rootDir>/node_modules/',
    '<rootDir>/src/core/routes/tests/api-key.routes.test.ts',
    '<rootDir>/src/core/routes/tests/auth.routes.test.ts',
    '<rootDir>/src/core/routes/tests/campaign.routes.test.ts',
    '<rootDir>/src/core/routes/tests/protected.routes.test.ts',
    '<rootDir>/src/email/routes/tests/email-campaign.routes.test.ts',
    '<rootDir>/src/email/routes/tests/email-transactional.routes.test.ts',
    '<rootDir>/src/sms/routes/tests/sms-callback.routes.test.ts',
    '<rootDir>/src/sms/routes/tests/sms-campaign.routes.test.ts',
    '<rootDir>/src/sms/routes/tests/sms-settings.routes.test.ts',
    '<rootDir>/src/sms/routes/tests/sms-transactional.routes.test.ts',
    '<rootDir>/src/telegram/routes/tests/telegram-campaign.routes.test.ts',
    '<rootDir>/src/telegram/routes/tests/telegram-settings.routes.test.ts',
  ],
  moduleNameMapper: {
    '@core/(.*)': '<rootDir>/src/core/$1',
    '@sms/(.*)': '<rootDir>/src/sms/$1',
    '@email/(.*)': '<rootDir>/src/email/$1',
    '@telegram/(.*)': '<rootDir>/src/telegram/$1',
    '@govsg/(.*)': '<rootDir>/src/govsg/$1',
    '@test-utils/(.*)': '<rootDir>/src/test-utils/$1',
    '@shared/(.*)': '<rootDir>/../shared/src/$1',
    '@mocks/(.*)': '<rootDir>/src/__mocks__/$1',
    "axios": "axios/dist/node/axios.cjs", // https://stackoverflow.com/a/74297004
  },
  modulePathIgnorePatterns: ['<rootDir>/build'],
  transform: {
    '^.+\\.(ts|tsx)$': 'ts-jest',
  },
  testEnvironment: 'node',
  globalSetup: '<rootDir>/src/test-utils/global-setup.ts',
  globalTeardown: '<rootDir>/src/test-utils/global-teardown.ts',
  setupFiles: ['<rootDir>/src/test-utils/test-env.ts'],
  setupFilesAfterEnv: ['<rootDir>/src/test-utils/setup.ts'],
}
