import * as aws from '@pulumi/aws'

const parameters =
[
	{
		'ParameterName': 'application_name',
		'Description': 'Sets the application name to be reported in statistics and logs.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'archive_command',
		'ParameterValue': '/etc/rds/dbbin/pgscripts/rds_wal_archive %p',
		'Description': 'Sets the shell command that will be called to archive a WAL file.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'archive_timeout',
		'ParameterValue': '300',
		'Description': '(s) Forces a switch to the next xlog file if a new file has not been started within N seconds.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-2147483647',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'array_nulls',
		'Description': 'Enable input of NULL elements in arrays.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'authentication_timeout',
		'Description': '(s) Sets the maximum allowed time to complete client authentication.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '1-600',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'auto_explain.log_analyze',
		'Description': 'Use EXPLAIN ANALYZE for plan logging.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'auto_explain.log_buffers',
		'Description': 'Log buffers usage.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'auto_explain.log_format',
		'Description': 'EXPLAIN format to be used for plan logging.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'text,xml,json,yaml',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'auto_explain.log_min_duration',
		'Description': '(ms) Sets the minimum execution time above which plans will be logged.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '-1-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'auto_explain.log_nested_statements',
		'Description': 'Log nested statements.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'auto_explain.log_timing',
		'Description': 'Collect timing data, not just row counts.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'auto_explain.log_triggers',
		'Description': 'Include trigger statistics in plans.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'auto_explain.log_verbose',
		'Description': 'Use EXPLAIN VERBOSE for plan logging.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'auto_explain.sample_rate',
		'Description': 'Fraction of queries to process.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'autovacuum',
		'Description': 'Starts the autovacuum subprocess.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'autovacuum_analyze_scale_factor',
		'ParameterValue': '0.05',
		'Description': 'Number of tuple inserts, updates or deletes prior to analyze as a fraction of reltuples.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-100',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'autovacuum_analyze_threshold',
		'Description': 'Minimum number of tuple inserts, updates or deletes prior to analyze.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'autovacuum_freeze_max_age',
		'Description': 'Age at which to autovacuum a table to prevent transaction ID wraparound.',
		'Source': 'engine-default',
		'ApplyType': 'static',
		'DataType': 'integer',
		'AllowedValues': '100000000-750000000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'autovacuum_max_workers',
		'ParameterValue': 'GREATEST({DBInstanceClassMemory/64371566592},3)',
		'Description': 'Sets the maximum number of simultaneously running autovacuum worker processes.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'integer',
		'AllowedValues': '1-8388607',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'autovacuum_multixact_freeze_max_age',
		'Description': 'Multixact age at which to autovacuum a table to prevent multixact wraparound.',
		'Source': 'engine-default',
		'ApplyType': 'static',
		'DataType': 'integer',
		'AllowedValues': '10000000-2000000000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'autovacuum_naptime',
		'ParameterValue': '15',
		'Description': '(s) Time to sleep between autovacuum runs.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '1-2147483',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'autovacuum_vacuum_cost_delay',
		'Description': '(ms) Vacuum cost delay in milliseconds, for autovacuum.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '-1-100',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'autovacuum_vacuum_cost_limit',
		'ParameterValue': 'GREATEST({log(DBInstanceClassMemory/21474836480)*600},200)',
		'Description': 'Vacuum cost amount available before napping, for autovacuum.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '-1-10000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'autovacuum_vacuum_scale_factor',
		'ParameterValue': '0.1',
		'Description': 'Number of tuple updates or deletes prior to vacuum as a fraction of reltuples.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-100',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'autovacuum_vacuum_threshold',
		'Description': 'Minimum number of tuple updates or deletes prior to vacuum.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'autovacuum_work_mem',
		'Description': '(kB) Sets the maximum memory to be used by each autovacuum worker process.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '-1-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'backend_flush_after',
		'Description': '(8Kb) Number of pages after which previously performed writes are flushed to disk.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-256',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'backslash_quote',
		'Description': 'Sets whether \\ is allowed in string literals.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'safe_encoding,on,off',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'bgwriter_delay',
		'Description': '(ms) Background writer sleep time between rounds.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '10-10000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'bgwriter_flush_after',
		'Description': '(8Kb) Number of pages after which previously performed writes are flushed to disk.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-256',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'bgwriter_lru_maxpages',
		'Description': 'Background writer maximum number of LRU pages to flush per round.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-1000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'bgwriter_lru_multiplier',
		'Description': 'Multiple of the average buffer usage to free per round.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-10',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'bytea_output',
		'Description': 'Sets the output format for bytea.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'escape,hex',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'check_function_bodies',
		'Description': 'Check function bodies during CREATE FUNCTION.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'checkpoint_completion_target',
		'ParameterValue': '0.9',
		'Description': 'Time spent flushing dirty buffers during checkpoint, as fraction of checkpoint interval.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'checkpoint_flush_after',
		'Description': '(8kB) Number of pages after which previously performed writes are flushed to disk.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-256',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'checkpoint_timeout',
		'Description': '(s) Sets the maximum time between automatic WAL checkpoints.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '30-3600',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'checkpoint_warning',
		'Description': '(s) Enables warnings if checkpoint segments are filled more frequently than this.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'client_encoding',
		'ParameterValue': 'UTF8',
		'Description': 'Sets the clients character set encoding.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'client_min_messages',
		'Description': 'Sets the message levels that are sent to the client.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'debug5,debug4,debug3,debug2,debug1,log,notice,warning,error',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'commit_delay',
		'Description': 'Sets the delay in microseconds between transaction commit and flushing WAL to disk.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-100000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'commit_siblings',
		'Description': 'Sets the minimum concurrent open transactions before performing commit_delay.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-1000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'config_file',
		'ParameterValue': '/rdsdbdata/config/postgresql.conf',
		'Description': 'Sets the servers main configuration file.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'string',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'constraint_exclusion',
		'Description': 'Enables the planner to use constraints to optimize queries.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'partition,on,off',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'cpu_index_tuple_cost',
		'Description': 'Sets the planners estimate of the cost of processing each index entry during an index scan.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1.79769e+308',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'cpu_operator_cost',
		'Description': 'Sets the planners estimate of the cost of processing each operator or function call.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1.79769e+308',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'cpu_tuple_cost',
		'Description': 'Sets the planners estimate of the cost of processing each tuple (row).',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1.79769e+308',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'cursor_tuple_fraction',
		'Description': 'Sets the planners estimate of the fraction of a cursors rows that will be retrieved.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'data_directory',
		'ParameterValue': '/rdsdbdata/db',
		'Description': 'Sets the servers data directory.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'string',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'datestyle',
		'Description': 'Sets the display format for date and time values.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'db_user_namespace',
		'Description': 'Enables per-database user names.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'deadlock_timeout',
		'Description': '(ms) Sets the time to wait on a lock before checking for deadlock.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '1-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'debug_pretty_print',
		'Description': 'Indents parse and plan tree displays.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'debug_print_parse',
		'Description': 'Logs each querys parse tree.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'debug_print_plan',
		'Description': 'Logs each querys execution plan.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'debug_print_rewritten',
		'Description': 'Logs each querys rewritten parse tree.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'default_statistics_target',
		'Description': 'Sets the default statistics target.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '1-10000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'default_tablespace',
		'Description': 'Sets the default tablespace to create tables and indexes in.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'default_transaction_deferrable',
		'Description': 'Sets the default deferrable status of new transactions.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'default_transaction_isolation',
		'Description': 'Sets the transaction isolation level of each new transaction.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'serializable,repeatable read,read committed,read uncommitted',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'default_transaction_read_only',
		'Description': 'Sets the default read-only status of new transactions.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'default_with_oids',
		'Description': 'Create new tables with OIDs by default.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'effective_cache_size',
		'ParameterValue': '{DBInstanceClassMemory/16384}',
		'Description': '(8kB) Sets the planners assumption about the size of the disk cache.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '1-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'effective_io_concurrency',
		'Description': 'Number of simultaneous requests that can be handled efficiently by the disk subsystem.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-1000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'enable_bitmapscan',
		'Description': 'Enables the planners use of bitmap-scan plans.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'enable_gathermerge',
		'Description': 'Enables the planner\'s use of gather merge plans.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'enable_hashagg',
		'Description': 'Enables the planners use of hashed aggregation plans.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'enable_hashjoin',
		'Description': 'Enables the planners use of hash join plans.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'enable_indexonlyscan',
		'Description': 'Enables the planner\'s use of index-only-scan plans.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'enable_indexscan',
		'Description': 'Enables the planners use of index-scan plans.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'enable_material',
		'Description': 'Enables the planners use of materialization.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'enable_mergejoin',
		'Description': 'Enables the planners use of merge join plans.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'enable_nestloop',
		'Description': 'Enables the planners use of nested-loop join plans.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'enable_parallel_append',
		'Description': 'Enables the planner\'s use of parallel append plans.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'enable_parallel_hash',
		'Description': 'Enables the planner\'s user of parallel hash plans.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'enable_partition_pruning',
		'Description': 'Enable plan-time and run-time partition pruning.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'enable_partitionwise_aggregate',
		'Description': 'Enables partitionwise aggregation and grouping.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'enable_partitionwise_join',
		'Description': 'Enables partitionwise join.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'enable_seqscan',
		'Description': 'Enables the planners use of sequential-scan plans.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'enable_sort',
		'Description': 'Enables the planners use of explicit sort steps.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'enable_tidscan',
		'Description': 'Enables the planners use of TID scan plans.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'escape_string_warning',
		'Description': 'Warn about backslash escapes in ordinary string literals.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'exit_on_error',
		'Description': 'Terminate session on any error.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'extra_float_digits',
		'Description': 'Sets the number of digits displayed for floating-point values.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '-15-3',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'force_parallel_mode',
		'Description': 'Forces use of parallel query facilities.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'from_collapse_limit',
		'Description': 'Sets the FROM-list size beyond which subqueries are not collapsed.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '1-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'fsync',
		'ParameterValue': '1',
		'Description': 'Forces synchronization of updates to disk.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'full_page_writes',
		'ParameterValue': '1',
		'Description': 'Writes full pages to WAL when first modified after a checkpoint.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'geqo',
		'Description': 'Enables genetic query optimization.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'geqo_effort',
		'Description': 'GEQO: effort is used to set the default for other GEQO parameters.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '1-10',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'geqo_generations',
		'Description': 'GEQO: number of iterations of the algorithm.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'geqo_pool_size',
		'Description': 'GEQO: number of individuals in the population.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'geqo_seed',
		'Description': 'GEQO: seed for random path selection.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'geqo_selection_bias',
		'Description': 'GEQO: selective pressure within the population.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '1.5-2',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'geqo_threshold',
		'Description': 'Sets the threshold of FROM items beyond which GEQO is used.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '2-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'gin_fuzzy_search_limit',
		'Description': 'Sets the maximum allowed result for exact search by GIN.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'gin_pending_list_limit',
		'Description': '(kB) Sets the maximum size of the pending list for GIN index.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '64-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'hba_file',
		'ParameterValue': '/rdsdbdata/config/pg_hba.conf',
		'Description': 'Sets the servers hba configuration file.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'string',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'hot_standby_feedback',
		'Description': 'Allows feedback from a hot standby to the primary that will avoid query conflicts.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'huge_pages',
		'ParameterValue': 'on',
		'Description': 'Use of huge pages on Linux.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'string',
		'AllowedValues': 'on,off',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'ident_file',
		'ParameterValue': '/rdsdbdata/config/pg_ident.conf',
		'Description': 'Sets the servers ident configuration file.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'string',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'idle_in_transaction_session_timeout',
		'ParameterValue': '86400000',
		'Description': '(ms) Sets the maximum allowed duration of any idling transaction.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'intervalstyle',
		'Description': 'Sets the display format for interval values.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'postgres,postgres_verbose,sql_standard,iso_8601',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'jit',
		'Description': 'Allow JIT compilation.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'jit_above_cost',
		'Description': 'Perform JIT compilation if query is more expensive.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '-1-1.79769e+308',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'jit_inline_above_cost',
		'Description': 'Perform JIT inlining if query is more expensive.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '-1-1.79769e+308',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'jit_optimize_above_cost',
		'Description': 'Optimize JITed functions if query is more expensive.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '-1-1.79769e+308',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'join_collapse_limit',
		'Description': 'Sets the FROM-list size beyond which JOIN constructs are not flattened.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '1-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'lc_messages',
		'Description': 'Sets the language in which messages are displayed.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'lc_monetary',
		'Description': 'Sets the locale for formatting monetary amounts.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'lc_numeric',
		'Description': 'Sets the locale for formatting numbers.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'lc_time',
		'Description': 'Sets the locale for formatting date and time values.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'listen_addresses',
		'ParameterValue': '*',
		'Description': 'Sets the host name or IP address(es) to listen to.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'string',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'lo_compat_privileges',
		'ParameterValue': '0',
		'Description': 'Enables backward compatibility mode for privilege checks on large objects.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_autovacuum_min_duration',
		'ParameterValue': '10000',
		'Description': '(ms) Sets the minimum execution time above which autovacuum actions will be logged.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '-1-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_checkpoints',
		'ParameterValue': '1',
		'Description': 'Logs each checkpoint.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_connections',
		'ParameterValue': '1',
		'Description': 'Logs each successful connection.',
		'Source': 'user',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'immediate',
	},
	{
		'ParameterName': 'log_destination',
		'ParameterValue': 'stderr',
		'Description': 'Sets the destination for server log output.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'stderr,csvlog',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_directory',
		'ParameterValue': '/rdsdbdata/log/error',
		'Description': 'Sets the destination directory for log files.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_disconnections',
		'Description': 'Logs end of a session, including duration.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_duration',
		'Description': 'Logs the duration of each completed SQL statement.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_error_verbosity',
		'Description': 'Sets the verbosity of logged messages.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'terse,default,verbose',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_executor_stats',
		'Description': 'Writes executor performance statistics to the server log.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_file_mode',
		'ParameterValue': '0644',
		'Description': 'Sets the file permissions for log files.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_filename',
		'ParameterValue': 'postgresql.log.%Y-%m-%d-%H',
		'Description': 'Sets the file name pattern for log files.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'postgresql.log.%Y-%m-%d,postgresql.log.%Y-%m-%d-%H',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'logging_collector',
		'ParameterValue': '1',
		'Description': 'Start a subprocess to capture stderr output and/or csvlogs into log files.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_hostname',
		'ParameterValue': '1',
		'Description': 'Logs the host name in the connection logs.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_line_prefix',
		'ParameterValue': '%t:%r:%u@%d:[%p]:',
		'Description': 'Controls information prefixed to each log line.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_lock_waits',
		'Description': 'Logs long lock waits.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_min_duration_statement',
		'Description': '(ms) Sets the minimum execution time above which statements will be logged.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '-1-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_min_error_statement',
		'Description': 'Causes all statements generating error at or above this level to be logged.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'debug5,debug4,debug3,debug2,debug1,info,notice,warning,error,log,fatal,panic',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_min_messages',
		'Description': 'Sets the message levels that are logged.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'debug5,debug4,debug3,debug2,debug1,info,notice,warning,error,log,fatal,panic',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_parser_stats',
		'Description': 'Writes parser performance statistics to the server log.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_planner_stats',
		'Description': 'Writes planner performance statistics to the server log.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_replication_commands',
		'Description': 'Logs each replication command.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_rotation_age',
		'ParameterValue': '60',
		'Description': '(min) Automatic log file rotation will occur after N minutes.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '1-1440',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_rotation_size',
		'Description': '(kB) Automatic log file rotation will occur after N kilobytes.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-2097151',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_statement',
		'Description': 'Sets the type of statements logged.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'none,ddl,mod,all',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_statement_stats',
		'Description': 'Writes cumulative performance statistics to the server log.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_temp_files',
		'Description': '(kB) Log the use of temporary files larger than this number of kilobytes.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '-1-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_timezone',
		'ParameterValue': 'UTC',
		'Description': 'Sets the time zone to use in log messages.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'log_truncate_on_rotation',
		'ParameterValue': '0',
		'Description': 'Truncate existing log files of same name during log rotation.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'maintenance_work_mem',
		'ParameterValue': 'GREATEST({DBInstanceClassMemory*1024/63963136},65536)',
		'Description': '(kB) Sets the maximum memory to be used for maintenance operations.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '1024-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'max_connections',
		'ParameterValue': 'LEAST({DBInstanceClassMemory/9531392},5000)',
		'Description': 'Sets the maximum number of concurrent connections.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'integer',
		'AllowedValues': '6-8388607',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'max_files_per_process',
		'Description': 'Sets the maximum number of simultaneously open files for each server process.',
		'Source': 'engine-default',
		'ApplyType': 'static',
		'DataType': 'integer',
		'AllowedValues': '25-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'max_locks_per_transaction',
		'ParameterValue': '64',
		'Description': 'Sets the maximum number of locks per transaction.',
		'Source': 'engine-default',
		'ApplyType': 'static',
		'DataType': 'integer',
		'AllowedValues': '10-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'max_logical_replication_workers',
		'Description': 'Maximum number of logical replication worker processes.',
		'Source': 'engine-default',
		'ApplyType': 'static',
		'DataType': 'integer',
		'AllowedValues': '0-262143',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'max_parallel_maintenance_workers',
		'Description': 'Sets the maximum number of parallel processes per maintenance operation.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-1024',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'max_parallel_workers',
		'Description': 'Sets the maximum number of parallel workers than can be active at one time.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-1024',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'max_parallel_workers_per_gather',
		'Description': 'Sets the maximum number of parallel processes per executor node.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-1024',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'max_pred_locks_per_page',
		'Description': 'Sets the maximum number of predicate-locked tuples per page.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'max_pred_locks_per_relation',
		'Description': 'Sets the maximum number of predicate-locked pages and tuples per relation.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '-2147483648-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'max_pred_locks_per_transaction',
		'Description': 'Sets the maximum number of predicate locks per transaction.',
		'Source': 'engine-default',
		'ApplyType': 'static',
		'DataType': 'integer',
		'AllowedValues': '10-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'max_prepared_transactions',
		'ParameterValue': '0',
		'Description': 'Sets the maximum number of simultaneously prepared transactions.',
		'Source': 'engine-default',
		'ApplyType': 'static',
		'DataType': 'integer',
		'AllowedValues': '0-8388607',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'max_replication_slots',
		'ParameterValue': '10',
		'Description': 'Sets the maximum number of replication slots that the server can support.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'integer',
		'AllowedValues': '5-8388607',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'max_stack_depth',
		'ParameterValue': '6144',
		'Description': '(kB) Sets the maximum stack depth, in kilobytes.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '100-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'max_standby_archive_delay',
		'Description': '(ms) Sets the maximum delay before canceling queries when a hot standby server is processing archived WAL data.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '-1-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'max_standby_streaming_delay',
		'Description': '(ms) Sets the maximum delay before canceling queries when a hot standby server is processing streamed WAL data.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '-1-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'max_sync_workers_per_subscription',
		'Description': 'Maximum number of synchronization workers per subscription',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-262143',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'max_wal_senders',
		'ParameterValue': '10',
		'Description': 'Sets the maximum number of simultaneously running WAL sender processes.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'integer',
		'AllowedValues': '5-8388607',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'max_wal_size',
		'ParameterValue': '2048',
		'Description': '(MB) Sets the WAL size that triggers a checkpoint.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '128-201326592',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'max_worker_processes',
		'ParameterValue': '8',
		'Description': 'Sets the maximum number of concurrent worker processes.',
		'Source': 'engine-default',
		'ApplyType': 'static',
		'DataType': 'integer',
		'AllowedValues': '0-262143',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'min_parallel_index_scan_size',
		'Description': '(8kB) Sets the minimum amount of index data for a parallel scan.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-715827882',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'min_parallel_table_scan_size',
		'Description': '(8kB) Sets the minimum amount of table data for a parallel scan.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-715827882',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'min_wal_size',
		'ParameterValue': '192',
		'Description': '(MB) Sets the minimum size to shrink the WAL to.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '128-201326592',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'old_snapshot_threshold',
		'Description': '(min) Time before a snapshot is too old to read pages changed after the snapshot was taken.',
		'Source': 'engine-default',
		'ApplyType': 'static',
		'DataType': 'integer',
		'AllowedValues': '-1-86400',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'operator_precedence_warning',
		'Description': 'Emit a warning for constructs that changed meaning since PostgreSQL 9.4.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'orafce.nls_date_format',
		'Description': 'Emulate oracle\'s date output behaviour.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'orafce.timezone',
		'Description': 'Specify timezone used for sysdate function.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'parallel_leader_participation',
		'Description': 'Controls whether Gather and Gather Merge also run subplans.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'parallel_setup_cost',
		'Description': 'Sets the planner\'s estimate of the cost of starting up worker processes for parallel query.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1.79769e+308',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'parallel_tuple_cost',
		'Description': 'Sets the planner\'s estimate of the cost of passing each tuple (row) from worker to master backend.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1.79769e+308',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'password_encryption',
		'ParameterValue': 'md5',
		'Description': 'Encrypt passwords.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'md5,scram-sha-256',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pgaudit.log',
		'Description': 'Specifies which classes of statements will be logged by session audit logging.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'list',
		'AllowedValues': 'ddl,function,misc,read,role,write,none,all,-ddl,-function,-misc,-read,-role,-write',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pgaudit.log_catalog',
		'Description': 'Specifies that session logging should be enabled in the case where all relations in a statement are in pg_catalog.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pgaudit.log_level',
		'Description': 'Specifies the log level that will be used for log entries.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'debug5,debug4,debug3,debug2,debug1,info,notice,warning,log',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pgaudit.log_parameter',
		'Description': 'Specifies that audit logging should include the parameters that were passed with the statement.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pgaudit.log_relation',
		'Description': 'Specifies whether session audit logging should create a separate log entry for each relation (TABLE, VIEW, etc.) referenced in a SELECT or DML statement.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pgaudit.log_statement_once',
		'Description': 'Specifies whether logging will include the statement text and parameters with the first log entry for a statement/substatement combination or with every entry.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pgaudit.role',
		'ParameterValue': 'rds_pgaudit',
		'Description': 'Specifies the master role to use for object audit logging.',
		'Source': 'user',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'rds_pgaudit',
		'IsModifiable': true,
		'ApplyMethod': 'immediate',
	},
	{
		'ParameterName': 'pg_hint_plan.debug_print',
		'Description': 'Logs results of hint parsing.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'off,on,detailed,verbose',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_hint_plan.enable_hint',
		'Description': 'Force planner to use plans specified in the hint comment preceding to the query.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_hint_plan.enable_hint_table',
		'Description': 'Force planner to not get hint by using table lookups.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_hint_plan.message_level',
		'Description': 'Message level of debug messages.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'debug5,debug4,debug3,debug2,debug1,log,info,notice,warning,error',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_hint_plan.parse_messages',
		'Description': 'Message level of parse errors.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'debug5,debug4,debug3,debug2,debug1,log,info,notice,warning,error',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pglogical.batch_inserts',
		'Description': 'Batch inserts if possible',
		'Source': 'engine-default',
		'ApplyType': 'static',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pglogical.conflict_log_level',
		'Description': 'Sets log level used for logging resolved conflicts.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'debug5,debug4,debug3,debug2,debug1,info,notice,warning,error,log,fatal,panic',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pglogical.conflict_resolution',
		'Description': 'Sets method used for conflict resolution for resolvable conflicts.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'error,apply_remote,keep_local,last_update_wins,first_update_wins',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pglogical.extra_connection_options',
		'Description': 'connection options to add to all peer node connections',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pglogical.synchronous_commit',
		'Description': 'pglogical specific synchronous commit value',
		'Source': 'engine-default',
		'ApplyType': 'static',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pglogical.use_spi',
		'Description': 'Use SPI instead of low-level API for applying changes',
		'Source': 'engine-default',
		'ApplyType': 'static',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_prewarm.autoprewarm',
		'Description': 'Starts the autoprewarm worker.',
		'Source': 'engine-default',
		'ApplyType': 'static',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'MinimumEngineVersion': '11.6',
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_prewarm.autoprewarm_interval',
		'Description': 'Sets the interval between dumps of shared buffers',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-2147483',
		'IsModifiable': true,
		'MinimumEngineVersion': '11.6',
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.block_is_normalized',
		'Description': 'Sets if the result value is normalized or not.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.block_threshold',
		'Description': 'Sets the threshold used by the Block similarity function.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.block_tokenizer',
		'Description': 'Sets the tokenizer for Block similarity function.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'alnum,gram,word,camelcase',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.cosine_is_normalized',
		'Description': 'Sets if the result value is normalized or not.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.cosine_threshold',
		'Description': 'Sets the threshold used by the Cosine similarity function.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.cosine_tokenizer',
		'Description': 'Sets the tokenizer for Cosine similarity function.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'alnum,gram,word,camelcase',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.dice_is_normalized',
		'Description': 'Sets if the result value is normalized or not.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.dice_threshold',
		'Description': 'Sets the threshold used by the Dice similarity measure.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.dice_tokenizer',
		'Description': 'Sets the tokenizer for Dice similarity measure.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'alnum,gram,word,camelcase',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.euclidean_is_normalized',
		'Description': 'Sets if the result value is normalized or not.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.euclidean_threshold',
		'Description': 'Sets the threshold used by the Euclidean similarity measure.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.euclidean_tokenizer',
		'Description': 'Sets the tokenizer for Euclidean similarity measure.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'alnum,gram,word,camelcase',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.hamming_is_normalized',
		'Description': 'Sets if the result value is normalized or not.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.hamming_threshold',
		'Description': 'Sets the threshold used by the Block similarity metric.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.jaccard_is_normalized',
		'Description': 'Sets if the result value is normalized or not.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.jaccard_threshold',
		'Description': 'Sets the threshold used by the Jaccard similarity measure.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.jaccard_tokenizer',
		'Description': 'Sets the tokenizer for Jaccard similarity measure.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'alnum,gram,word,camelcase',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.jaro_is_normalized',
		'Description': 'Sets if the result value is normalized or not.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.jaro_threshold',
		'Description': 'Sets the threshold used by the Jaro similarity measure.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.jarowinkler_is_normalized',
		'Description': 'Sets if the result value is normalized or not.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.jarowinkler_threshold',
		'Description': 'Sets the threshold used by the Jarowinkler similarity measure.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.levenshtein_is_normalized',
		'Description': 'Sets if the result value is normalized or not.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.levenshtein_threshold',
		'Description': 'Sets the threshold used by the Levenshtein similarity measure.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.matching_is_normalized',
		'Description': 'Sets if the result value is normalized or not.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.matching_threshold',
		'Description': 'Sets the threshold used by the Matching Coefficient similarity measure.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.matching_tokenizer',
		'Description': 'Sets the tokenizer for Matching Coefficient similarity measure.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'alnum,gram,word,camelcase',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.mongeelkan_is_normalized',
		'Description': 'Sets if the result value is normalized or not.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.mongeelkan_threshold',
		'Description': 'Sets the threshold used by the Monge-Elkan similarity measure.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.mongeelkan_tokenizer',
		'Description': 'Sets the tokenizer for Monge-Elkan similarity measure.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'alnum,gram,word,camelcase',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.nw_gap_penalty',
		'Description': 'Sets the gap penalty used by the Needleman-Wunsch similarity measure.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '-9223370000000000000-9223370000000000000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.nw_is_normalized',
		'Description': 'Sets if the result value is normalized or not.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.nw_threshold',
		'Description': 'Sets the threshold used by the Needleman-Wunsch similarity measure.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.overlap_is_normalized',
		'Description': 'Sets if the result value is normalized or not.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.overlap_threshold',
		'Description': 'Sets the threshold used by the Overlap Coefficient similarity measure.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.overlap_tokenizer',
		'Description': 'Sets the tokenizer for Overlap Coefficientsimilarity measure.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'alnum,gram,word,camelcase',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.qgram_is_normalized',
		'Description': 'Sets if the result value is normalized or not.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.qgram_threshold',
		'Description': 'Sets the threshold used by the Q-Gram similarity measure.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.qgram_tokenizer',
		'Description': 'Sets the tokenizer for Q-Gram measure.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'alnum,gram,word,camelcase',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.swg_is_normalized',
		'Description': 'Sets if the result value is normalized or not.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.swg_threshold',
		'Description': 'Sets the threshold used by the Smith-Waterman-Gotoh similarity measure.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.sw_is_normalized',
		'Description': 'Sets if the result value is normalized or not.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_similarity.sw_threshold',
		'Description': 'Sets the threshold used by the Smith-Waterman similarity measure.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_stat_statements.max',
		'Description': 'Sets the maximum number of statements tracked by pg_stat_statements.',
		'Source': 'engine-default',
		'ApplyType': 'static',
		'DataType': 'integer',
		'AllowedValues': '100-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_stat_statements.save',
		'Description': 'Save pg_stat_statements statistics across server shutdowns.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_stat_statements.track',
		'Description': 'Selects which statements are tracked by pg_stat_statements.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'NONE,TOP,ALL',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_stat_statements.track_utility',
		'Description': 'Selects whether utility commands are tracked by pg_stat_statements.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_transport.num_workers',
		'Description': 'Number of workers to use for a physical transport.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '1-32',
		'IsModifiable': true,
		'MinimumEngineVersion': '11.5',
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_transport.timing',
		'Description': 'Specifies whether to report timing information during transport.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'MinimumEngineVersion': '11.5',
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'pg_transport.work_mem',
		'Description': '(kB) Amount of memory each worker can allocate for a physical transport.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '65536-2147483647',
		'IsModifiable': true,
		'MinimumEngineVersion': '11.5',
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'port',
		'ParameterValue': '{EndPointPort}',
		'Description': 'Sets the TCP port the server listens on.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'integer',
		'AllowedValues': '1-65535',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'postgis.gdal_enabled_drivers',
		'ParameterValue': 'ENABLE_ALL',
		'Description': 'Enable for disable GDAL drivers used with PostGIS in Postgres 9.3.5 and above.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'string',
		'AllowedValues': 'ENABLE_ALL,DISABLE_ALL',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'quote_all_identifiers',
		'Description': 'When generating SQL fragments, quote all identifiers.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'random_page_cost',
		'Description': 'Sets the planners estimate of the cost of a nonsequentially fetched disk page.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1.79769e+308',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'rds.adaptive_autovacuum',
		'ParameterValue': '1',
		'Description': 'RDS parameter to enable/disable adaptive autovacuum.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'rds.custom_dns_resolution',
		'ParameterValue': '0',
		'Description': 'Allow DNS resolution in Customer VPC.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'rds.extensions',
		'ParameterValue': 'address_standardizer, address_standardizer_data_us, amcheck, aws_commons, aws_s3, bloom, btree_gin, btree_gist, citext, cube, dblink, dict_int, dict_xsyn, earthdistance, fuzzystrmatch, hll, hstore, hstore_plperl, intagg, intarray, ip4r, isn, jsonb_plperl, log_fdw, ltree, orafce, pageinspect, pgaudit, pgcrypto, pglogical, pgrouting, pgrowlocks, pgstattuple, pgtap, pg_buffercache, pg_freespacemap, pg_hint_plan, pg_prewarm, pg_repack, pg_similarity, pg_stat_statements, pg_transport, pg_trgm, pg_visibility, plcoffee, plls, plperl, plpgsql, plprofiler, pltcl, plv8, postgis, postgis_tiger_geocoder, postgis_topology, postgres_fdw, prefix, sslinfo, tablefunc, test_parser, tsm_system_rows, tsm_system_time, unaccent, uuid-ossp',
		'Description': 'List of extensions provided by RDS',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'string',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'rds.force_admin_logging_level',
		'Description': 'See log messages for RDS admin user actions in customer databases.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'disabled,debug5,debug4,debug3,debug2,debug1,info,notice,warning,error,log,fatal,panic',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'rds.force_autovacuum_logging_level',
		'ParameterValue': 'INFO',
		'Description': 'See log messages related to autovacuum operations.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'disabled,debug5,debug4,debug3,debug2,debug1,info,notice,warning,error,log,fatal,panic',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'rds.force_ssl',
		'ParameterValue': '1',
		'Description': 'Force SSL connections.',
		'Source': 'user',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'immediate',
	},
	{
		'ParameterName': 'rds.logical_replication',
		'ParameterValue': '0',
		'Description': 'Enables logical decoding.',
		'Source': 'engine-default',
		'ApplyType': 'static',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'rds.log_retention_period',
		'ParameterValue': '4320',
		'Description': 'Amazon RDS will delete PostgreSQL log that are older than N minutes.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '1440-10080',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'rds.max_tcp_buffers',
		'ParameterValue': '33554432',
		'Description': 'Sets the maximum size for tcp buffers.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '4096-1000000000',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'rds.pg_stat_ramdisk_size',
		'ParameterValue': '0',
		'Description': 'Size of the stats ramdisk in MB. A nonzero value signals HM to set up the ramdisk.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'integer',
		'AllowedValues': '0-8196',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'rds.rds_superuser_reserved_connections',
		'ParameterValue': '2',
		'Description': 'Sets the number of connection slots reserved for rds_superusers.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'integer',
		'AllowedValues': '0-8388607',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'rds.restrict_password_commands',
		'Description': 'restricts password-related commands to members of rds_password',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'rds.superuser_variables',
		'ParameterValue': 'session_replication_role',
		'Description': 'List of superuser-only variables for which we elevate rds_superuser modification statements.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'string',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'restart_after_crash',
		'Description': 'Reinitialize server after backend crash.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'row_security',
		'Description': 'Enable row security.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'search_path',
		'Description': 'Sets the schema search order for names that are not schema-qualified.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'seq_page_cost',
		'Description': 'Sets the planners estimate of the cost of a sequentially fetched disk page.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'float',
		'AllowedValues': '0-1.79769e+308',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'server_encoding',
		'Description': 'Sets the server (database) character set encoding.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'string',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'session_replication_role',
		'Description': 'Sets the sessions behavior for triggers and rewrite rules.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'origin,replica,local',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'shared_buffers',
		'ParameterValue': '{DBInstanceClassMemory/32768}',
		'Description': '(8kB) Sets the number of shared memory buffers used by the server.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'integer',
		'AllowedValues': '16-1073741823',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'shared_preload_libraries',
		'ParameterValue': 'pg_stat_statements,pgaudit',
		'Description': 'Lists shared libraries to preload into server.',
		'Source': 'user',
		'ApplyType': 'static',
		'DataType': 'list',
		'AllowedValues': 'auto_explain,orafce,pgaudit,pglogical,pg_hint_plan,pg_prewarm,pg_similarity,pg_stat_statements,pg_transport,plprofiler',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'ssl',
		'ParameterValue': '1',
		'Description': 'Enables SSL connections.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'ssl_ca_file',
		'ParameterValue': '/rdsdbdata/rds-metadata/ca-cert.pem',
		'Description': 'Location of the SSL server authority file.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'ssl_cert_file',
		'ParameterValue': '/rdsdbdata/rds-metadata/server-cert.pem',
		'Description': 'Location of the SSL server certificate file.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'ssl_ciphers',
		'Description': 'Sets the list of allowed SSL ciphers.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'ssl_key_file',
		'ParameterValue': '/rdsdbdata/rds-metadata/server-key.pem',
		'Description': 'Location of the SSL server private key file',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'standard_conforming_strings',
		'Description': 'Causes ... strings to treat backslashes literally.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'statement_timeout',
		'Description': '(ms) Sets the maximum allowed duration of any statement.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'stats_temp_directory',
		'ParameterValue': '/rdsdbdata/db/pg_stat_tmp',
		'Description': 'Writes temporary statistics files to the specified directory.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'superuser_reserved_connections',
		'ParameterValue': '3',
		'Description': 'Sets the number of connection slots reserved for superusers.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'integer',
		'AllowedValues': '0-8388607',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'synchronize_seqscans',
		'Description': 'Enable synchronized sequential scans.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'synchronous_commit',
		'ParameterValue': 'on',
		'Description': 'Sets the current transactions synchronization level.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'local,on,off',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'syslog_facility',
		'Description': 'Sets the syslog facility to be used when syslog enabled.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'local0,local1,local2,local3,local4,local5,local6,local7',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'tcp_keepalives_count',
		'Description': 'Maximum number of TCP keepalive retransmits.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'tcp_keepalives_idle',
		'Description': '(s) Time between issuing TCP keepalives.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'tcp_keepalives_interval',
		'Description': '(s) Time between TCP keepalive retransmits.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'temp_buffers',
		'Description': '(8kB) Sets the maximum number of temporary buffers used by each session.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '100-1073741823',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'temp_file_limit',
		'Description': '(kB) Limits the total size of all temporary files used by each process.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '-1-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'temp_tablespaces',
		'Description': 'Sets the tablespace(s) to use for temporary tables and sort files.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'timezone',
		'ParameterValue': 'UTC',
		'Description': 'Sets the time zone for displaying and interpreting time stamps.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'track_activities',
		'Description': 'Collects information about executing commands.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'track_activity_query_size',
		'ParameterValue': '4096',
		'Description': 'Sets the size reserved for pg_stat_activity.current_query, in bytes.',
		'Source': 'engine-default',
		'ApplyType': 'static',
		'DataType': 'integer',
		'AllowedValues': '100-102400',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'track_commit_timestamp',
		'Description': 'Collects transaction commit time.',
		'Source': 'engine-default',
		'ApplyType': 'static',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'track_counts',
		'Description': 'Collects statistics on database activity.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'track_functions',
		'ParameterValue': 'pl',
		'Description': 'Collects function-level statistics on database activity.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'none,pl,all',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'track_io_timing',
		'ParameterValue': '1',
		'Description': 'Collects timing statistics on database IO activity.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'transform_null_equals',
		'Description': 'Treats expr=NULL as expr IS NULL.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'unix_socket_directories',
		'ParameterValue': '/tmp',
		'Description': 'Sets the directory where the Unix-domain socket will be created.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'string',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'unix_socket_group',
		'ParameterValue': 'rdsdb',
		'Description': 'Sets the owning group of the Unix-domain socket.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'string',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'unix_socket_permissions',
		'ParameterValue': '0700',
		'Description': 'Sets the access permissions of the Unix-domain socket.',
		'Source': 'system',
		'ApplyType': 'static',
		'DataType': 'integer',
		'AllowedValues': '0-511',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'update_process_title',
		'Description': 'Updates the process title to show the active SQL command.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'vacuum_cleanup_index_scale_factor',
		'Description': 'Number of tuple inserts prior to index cleanup as a fraction of reltuples.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-10000000000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'vacuum_cost_delay',
		'Description': '(ms) Vacuum cost delay in milliseconds.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-100',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'vacuum_cost_limit',
		'Description': 'Vacuum cost amount available before napping.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '1-10000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'vacuum_cost_page_dirty',
		'Description': 'Vacuum cost for a page dirtied by vacuum.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-10000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'vacuum_cost_page_hit',
		'Description': 'Vacuum cost for a page found in the buffer cache.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-10000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'vacuum_cost_page_miss',
		'ParameterValue': '5',
		'Description': 'Vacuum cost for a page not found in the buffer cache.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-10000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'vacuum_defer_cleanup_age',
		'Description': 'Number of transactions by which VACUUM and HOT cleanup should be deferred, if any.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-1000000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'vacuum_freeze_min_age',
		'Description': 'Minimum age at which VACUUM should freeze a table row.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-1000000000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'vacuum_freeze_table_age',
		'Description': 'Age at which VACUUM should scan whole table to freeze tuples.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-2000000000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'vacuum_multixact_freeze_min_age',
		'Description': 'Minimum age at which VACUUM should freeze a MultiXactId in a table row.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-1000000000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'vacuum_multixact_freeze_table_age',
		'Description': 'Multixact age at which VACUUM should scan whole table to freeze tuples.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-2000000000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'wal_buffers',
		'Description': '(8kB) Sets the number of disk-page buffers in shared memory for WAL.',
		'Source': 'engine-default',
		'ApplyType': 'static',
		'DataType': 'integer',
		'AllowedValues': '-1-262143',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'wal_compression',
		'Description': 'Compresses full-page writes written in WAL file.',
		'Source': 'engine-default',
		'ApplyType': 'static',
		'DataType': 'boolean',
		'AllowedValues': '0,1',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'wal_keep_segments',
		'ParameterValue': '32',
		'Description': 'Sets the number of WAL files held for standby servers.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'wal_receiver_status_interval',
		'Description': '(s) Sets the maximum interval between WAL receiver status reports to the primary.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-2147483',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'wal_receiver_timeout',
		'ParameterValue': '30000',
		'Description': '(ms) Sets the maximum wait time to receive data from the primary.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-3600000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'wal_sender_timeout',
		'ParameterValue': '30000',
		'Description': '(ms) Sets the maximum time to wait for WAL replication.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-3600000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'wal_sync_method',
		'Description': 'Selects the method used for forcing WAL updates to disk.',
		'Source': 'system',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'fsync,fdatasync,open_sync,open_datasync',
		'IsModifiable': false,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'wal_writer_delay',
		'Description': '(ms) WAL writer sleep time between WAL flushes.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '1-10000',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'wal_writer_flush_after',
		'Description': '(8Kb) Amount of WAL written out by WAL writer triggering a flush.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '0-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'work_mem',
		'Description': '(kB) Sets the maximum memory to be used for query workspaces.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'integer',
		'AllowedValues': '64-2147483647',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'xmlbinary',
		'Description': 'Sets how binary values are to be encoded in XML.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'base64,hex',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	},
	{
		'ParameterName': 'xmloption',
		'Description': 'Sets whether XML data in implicit parsing and serialization operations is to be considered as documents or content fragments.',
		'Source': 'engine-default',
		'ApplyType': 'dynamic',
		'DataType': 'string',
		'AllowedValues': 'content,document',
		'IsModifiable': true,
		'ApplyMethod': 'pending-reboot',
	}
]



export const postgres11WithAudit: aws.types.input.rds.ParameterGroupParameter[] = parameters
	.filter(o=>o.ParameterValue !== undefined && o.IsModifiable)
	.map(o=>{
		return { name: o.ParameterName, value: o.ParameterValue || '', applyMethod: o.ApplyMethod, }
	})