export * as GovsgService from './govsg.service'
export * as GovsgTemplateService from './govsg-template.service'
export * as GovsgStatsService from './govsg-stats.service'
export * as GovsgTransactionalService from './govsg-transactional.service'
export * as GovsgVerificationService from './govsg-verification-service'
