openapi: 3.0.0
info:
  title: Postman
  version: v1,
  description: Postman API
  license:
    name: MIT
    url: https://choosealicense.com/licenses/mit/
servers:
  - url: /v1
    description: Postman v1 API
paths:
  /campaigns:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - Campaigns
      summary: List all campaigns for user
      parameters:
        - in: query
          name: limit
          description: max number of campaigns returned
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
        - in: query
          name: offset
          description: offset to begin returning campaigns from
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
        - in: query
          name: type
          description: mode of campaigns to filter for
          required: false
          schema:
            type: string
            enum: [ EMAIL, SMS, TELEGRAM ]
        - in: query
          name: status
          description: status of campaigns to filter for
          required: false
          schema:
            type: string
            enum: [ Draft, Sending, Sent ]
        - in: query
          name: name
          description: name of campaigns to filter for
          required: false
          schema:
            type: string
        - in: query
          name: sort_by
          description: field used to sort campaigns
          required: false
          schema:
            type: string
            enum: [ created_at, sent_at ]
            default: created_at
        - in: query
          name: order_by
          description: order to sort campaigns by
          required: false
          schema:
            type: string
            enum: [ ASC, DESC ]
            default: DESC
      responses:
        "200":
          description: List of campaigns
          content:
            application/json:
              schema:
                type: object
                properties:
                  campaigns:
                    type: array
                    items:
                      $ref: '#/components/schemas/CampaignMeta'
                  total_count:
                    type: integer
        "401":
          description: Unauthorized
        "403":
          description: Forbidden. Request violates firewall rules.
        "429":
          description: Rate limit exceeded. Too many requests.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorStatus'
              example:
                { status: 429, message: Too many requests. Please try again later. }
        "500":
          description: Internal Server Error
          content:
            text/plain:
              example: Internal Server Error
        "502":
          description: Bad Gateway
        "504":
          description: Gateway Timeout
        "503":
          description: Service Temporarily Unavailable
        "520":
          description: Web Server Returns An Unknown Error
        "521":
          description: Web Server Is Down
        "522":
          description: Connection Timed Out
        "523":
          description: Origin Is Unreachable
        "524":
          description: A Timeout occurred
        "525":
          description: SSL handshake failed
        "526":
          description: Invalid SSL certificate
    post:
      security:
        - bearerAuth: [ ]
      summary: Create a new campaign
      tags:
        - Campaigns
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                type:
                  $ref: '#/components/schemas/ChannelType'
              required:
                - name
                - type

      responses:
        "201":
          description: Campaign created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignMeta'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden. Request violates firewall rules.
        "429":
          description: Rate limit exceeded. Too many requests.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorStatus'
              example:
                { status: 429, message: Too many requests. Please try again later. }
        "500":
          description: Internal Server Error
          content:
            text/plain:
              example: Internal Server Error
        "502":
          description: Bad Gateway
        "504":
          description: Gateway Timeout
        "503":
          description: Service Temporarily Unavailable
        "520":
          description: Web Server Returns An Unknown Error
        "521":
          description: Web Server Is Down
        "522":
          description: Connection Timed Out
        "523":
          description: Origin Is Unreachable
        "524":
          description: A Timeout occurred
        "525":
          description: SSL handshake failed
        "526":
          description: Invalid SSL certificateÏ
  /campaigns/{campaignId}:
    delete:
      security:
        - bearerAuth: []
      tags:
        - Campaigns
      summary: Delete a campaign using its ID
      parameters:
        - in: path
          name: campaignId
          description: ID of the campaign
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        "200":
          description: Successfully deleted
          content:
            schema: {} # TODO
        "401":
          description: Unauthorized
        "404":
          description: Campaign not found
        "403":
          description: Forbidden. Request violates firewall rules.
        "429":
          description: Rate limit exceeded. Too many requests.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorStatus'
              example:
                {status: 429, message: Too many requests. Please try again later.}
        "500":
          description: Internal Server Error
          content:
            text/plain:
              example: Internal Server Error
        "502":
          description: Bad Gateway
        "504":
          description: Gateway Timeout
        "503":
          description: Service Temporarily Unavailable
        "520":
          description: Web Server Returns An Unknown Error
        "521":
          description: Web Server Is Down
        "522":
          description: Connection Timed Out
        "523":
          description: Origin Is Unreachable
        "524":
          description: A Timeout occurred
        "525":
          description: SSL handshake failed
        "526":
          description: Invalid SSL certificate
    put:
      security:
        - bearerAuth: [ ]
      summary: Rename campaign
      tags:
        - Campaigns
      parameters:
        - name: campaignId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                should_save_list:
                  type: boolean
      responses:
        "200":
          description: Campaign renamed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignMeta'
        "401":
          description: Unauthorized
        "404":
          description: Not found
        "403":
          description: Forbidden. Request violates firewall rules.
        "429":
          description: Rate limit exceeded. Too many requests.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorStatus'
              example:
                { status: 429, message: Too many requests. Please try again later. }
        "500":
          description: Internal Server Error
          content:
            text/plain:
              example: Internal Server Error
        "502":
          description: Bad Gateway
        "504":
          description: Gateway Timeout
        "503":
          description: Service Temporarily Unavailable
        "520":
          description: Web Server Returns An Unknown Error
        "521":
          description: Web Server Is Down
        "522":
          description: Connection Timed Out
        "523":
          description: Origin Is Unreachable
        "524":
          description: A Timeout occurred
        "525":
          description: SSL handshake failed
        "526":
          description: Invalid SSL certificateÏ

components:
  schemas:
  # TODO

