name: Deploy frontend to AWS Amplify
on:
  push:
    branches:
      - staging
      - master

# Making sure that the current deployment is completed before the next one
concurrency: deploy-frontend-${{ github.ref }}
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Extract branch name
        shell: bash
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            echo "##[set-output name=branch;]master"
          else
            echo "##[set-output name=branch;]staging"
          fi
        id: extract_branch
      - name: Deploy
        shell: bash
        env:
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
          APP_ID: d3k3b7zs07zjio
        run: ./scripts/amplify-deploy.sh $APP_ID $BRANCH
