name: Deploy frontend to AWS Amplify
on:
  workflow_call:
    inputs:
      environment:
        description: "staging or production"
        required: true
        type: string
    outputs:
      revert_command:
        description: "Command to revert frontend deployment"
        value: ${{ jobs.deploy-frontend.outputs.revert_cmd }}
env:
  APP_ID: d3k3b7zs07zjio
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ inputs.environment == 'production' && 'master' || 'staging' }}
    outputs:
      revert_cmd: ${{ steps.generate-revert-command.outputs.revert_cmd }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
      - name: Generate revert command
        id: generate-revert-command
        run: |
          aws amplify list-jobs --app-id $APP_ID --branch-name $BRANCH --max-items 1 | jq '.jobSummaries[0]' | echo
          JOB_ID=$(aws amplify list-jobs --app-id $APP_ID --branch-name $BRANCH --max-items 1 | jq '.jobSummaries[0].jobId')
          echo "revert_cmd=aws amplify start-job --app-id $APP_ID --branch-name $BRANCH --job-id $JOB_ID --job-type RETRY" >> $GITHUB_OUTPUT
      - name: Deploy
        shell: bash
        env:
          COMMIT_ID: ${{ github.sha }}
        run: ./scripts/amplify-deploy.sh $APP_ID $BRANCH $COMMIT_ID
